#!/usr/bin/env bash
#A script to stop a previous process
process_id=$(pgrep 4-to_infinity_and_beyond)

# If the process ID is not empty, stop the process
if [[ -n "$process_id" ]]; then
  kill -9 "$process_id"
fi
